import React from 'react';
import Head from 'next/head'
import Image from 'next/image'
import NavBar from './NavBar';
import { Footer } from '.';
import UnderLine from './UnderLine';
import NavBanner from './NavBanner';

const Layout = ({children}) => {
    return (
        <div>
            <Head>
                <title>CD</title>
                <meta name="description" content="Generated by create next app" />
                <link
                    rel="stylesheet"
                    href="https://fonts.googleapis.com/icon?family=Material+Icons"
                />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
                <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@200;300;400;500;600;700;800&display=swap" rel="stylesheet" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className="header">
                <NavBar />
                <UnderLine />
                <NavBanner />
            </header>
            <main>
                {children}
            </main>
            <footer className="footer">
                <Footer />
            </footer>
        </div>
    )
}

export default Layout
